### ISSUE TITLE
Remove legacy gem from Rubygems

### ISSUE THREAD

**Issue by jclay** [vijendra/checkr#7]
@vijendra Are you able to remove the legacy gem from Ruby gems using the [gem yank](http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem) method?

We should remove it to prevent new users from running the old version which has a pretty serious issue that can be hard to debug. (#5) We can also free up the namespace for the [official Checkr gem](https://github.com/checkr/checkr-ruby).

**Comment by joncalhoun** [comment]
Alternatively if you give me ownership on rubygems (joncalhoun@gmail.com) I can push a new version there that has a new major version number.
